apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  type: NodePort
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 80        # پورت سرویس درون خوشه
      targetPort: 5000  # پورت اپلیکیشن در پاد
